Creating /home/opsiproducts in postinst.
Releasing to experimental

diff --git a/debian/opsi-depotserver.postinst b/debian/opsi-depotserver.postinst
--- a/debian/opsi-depotserver.postinst
+++ b/debian/opsi-depotserver.postinst
@@ -40,6 +40,10 @@ fi
 case "$1" in
 	configure)
 
+		if [ ! -d "/home/opsiproducts" ]; then
+			mkdir -p /home/opsiproducts || echo "Creating /home/opsiproducts failed!"
+		fi
+
 		arguments=""
 		if [ "$CONFIGURE_DHCPD" = "true" ]; then
 			arguments="${arguments} --auto-configure-dhcpd"
