tagged 3.3-9

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -105,19 +105,15 @@ case "$1" in
 			cat /var/lib/opsi/config/global.ini.tmp | sed "s/@FQDN@/$FQDN/g" > /var/lib/opsi/config/global.ini
 			rm /var/lib/opsi/config/global.ini.tmp
 		fi
-	fi
-	
-	$VERBOSE && echo -e "\nAdding system users and groups..."
-	
-	# add system group pcpatch and users pcpatch
-	$VERBOSE && echo "  -> Adding group pcpatch"
-	if [ -z "`getent group pcpatch`" ]; then
-		groupadd -g 992 pcpatch
-	fi
-		
-	$VERBOSE && echo "  -> Adding user pcpatch"
-	if [ -z "`getent passwd pcpatch`" ]; then
-		useradd -u 992 -g 992 -d /opt/pcbin/pcpatch -s /bin/bash pcpatch
+		set +e
+		grep "@IPADDRESS@" /var/lib/opsi/config/global.ini >/dev/null 2>/dev/null	
+		status=$?
+		set -e
+		if [ $status = 0 ]; then
+			cp /var/lib/opsi/config/global.ini /var/lib/opsi/config/global.ini.tmp
+			cat /var/lib/opsi/config/global.ini.tmp | sed "s/@IPADDRESS@/$IPADDRESS/g" > /var/lib/opsi/config/global.ini
+			rm /var/lib/opsi/config/global.ini.tmp
+		fi
 	fi
 	
 	if ! [ -e /var/lib/opsi/config/depots/$FQDN ]; then
@@ -126,22 +122,24 @@ case "$1" in
 	
 	# file permissions
 	$VERBOSE && echo -e "\nSetting permissions..."
-	chown -R pcpatch:pcpatch /etc/opsi/backendManager.d
+	chown -R opsiconfd:pcpatch /etc/opsi/backendManager.d
 	chmod 0660 /etc/opsi/backendManager.d/*
-	chown -R pcpatch:pcpatch /opt/pcbin/pcpatch
+	chown -R opsiconfd:pcpatch /opt/pcbin/pcpatch
 	chmod 2770 /opt/pcbin/pcpatch
-	chown -R pcpatch:pcpatch /opt/pcbin/pcpatch/pclog
+	chown -R opsiconfd:pcpatch /opt/pcbin/pcpatch/pclog
 	chmod 2770 /opt/pcbin/pcpatch/pclog
-	chown -R pcpatch:pcpatch /opt/pcbin/utils
+	chown -R opsiconfd:pcpatch /opt/pcbin/utils
 	chmod 2770 /opt/pcbin/utils
-	chown -R pcpatch:pcpatch /opt/pcbin/install
+	chown -R opsiconfd:pcpatch /opt/pcbin/install
 	chmod 2770 /opt/pcbin/install
-	chown -R root:pcpatch /tftpboot/linux
+	chown -R opsiconfd:pcpatch /tftpboot/linux
 	chmod 2775 /tftpboot/linux
 	chmod 2775 /tftpboot/linux/pxelinux.cfg
 	find /tftpboot/linux -type f -exec chmod 664 {} \;
-	chown -R pcpatch:pcpatch /var/lib/opsi
+	chown -R opsiconfd:pcpatch /var/lib/opsi
 	chmod 2750 /var/lib/opsi
+	# for ssh public key authentification to work rights on /var/lib/opsi have to be pcatch:pcpatch 750
+	chown pcpatch /var/lib/opsi
 	chmod 2770 /var/lib/opsi/products
 	chmod 0660 /var/lib/opsi/products/* >/dev/null 2>/dev/null || true
 	chmod 2770 /var/lib/opsi/config
@@ -150,8 +148,14 @@ case "$1" in
 	chmod 2770 /var/lib/opsi/config/depots
 	chmod 2770 -R /var/lib/opsi/config/depots
 	find /var/lib/opsi/config/depots -type f -exec chmod 660 {} \;
+	chmod 2770 /var/lib/opsi/audit
+	chmod 0660 /var/lib/opsi/audit/* >/dev/null 2>/dev/null || true
 	chmod 0660 /var/lib/opsi/config/templates/pcproto.ini
 	chmod 0660 /var/lib/opsi/config/global.ini
+	chown opsiconfd:pcpatch /var/log/opsi
+	chmod 2770 /var/log/opsi
+	chown pcpatch:pcpatch /home/opsiproducts
+	chmod 2770 /home/opsiproducts
 	
 	db_get opsi/configure_samba
 	if [ "$RET" = "true" ]; then
@@ -201,6 +205,26 @@ case "$1" in
 				echo " path = /var/lib/opsi/config" 	>> /etc/samba/smb.conf
 				echo " writeable = yes" 		>> /etc/samba/smb.conf
 				echo " invalid users = root" 		>> /etc/samba/smb.conf
+			fi
+			
+			$VERBOSE && echo "  -> Testing if share [opsi_workbench] already exists"
+			set +e
+			grep "^\[opsi_workbench\]" /etc/samba/smb.conf >/dev/null 2>/dev/null
+			status=$?
+			set -e
+			if [ $status = 0 ]; then
+				$VERBOSE && echo "      * share exists"
+			else
+				$VERBOSE && echo "      * adding share"
+				echo "" 				>> /etc/samba/smb.conf
+				echo "[opsi_workbench]" 		>> /etc/samba/smb.conf
+				echo " available = yes"			>> /etc/samba/smb.conf
+				echo " comment = opsi workbench" 	>> /etc/samba/smb.conf
+				echo " path = /home/opsiproducts" 	>> /etc/samba/smb.conf
+				echo " writeable = yes" 		>> /etc/samba/smb.conf
+				echo " invalid users = root" 		>> /etc/samba/smb.conf
+				echo " create mask = 0660"		>> /etc/samba/smb.conf
+				echo " directory mask = 0770"		>> /etc/samba/smb.conf
 			fi
 		else
 			echo "        * /etc/samba/smb.conf not found!"
@@ -332,15 +356,25 @@ EOF
 	set -e
 	if [ $status != 0 ]; then
 		# No password set
+		/usr/bin/opsi-admin -d method createOpsiBase >/dev/null 2>/dev/null	
+		
 		/usr/bin/opsi-admin -d method createServer "$HOSTNAME" "$DOMAIN" > /dev/null
 		
 		db_get opsi/pcpatch_password1
 		/usr/bin/opsi-admin -d task setPcpatchPassword $RET
 	fi
 	
-	chown pcpatch:pcpatch /etc/opsi/pckeys
+	test -e /var/lib/opsi/.ssh && rm -r /var/lib/opsi/.ssh
+	/usr/bin/opsi-admin -d method getPcpatchRSAPrivateKey >/dev/null 2>/dev/null || true
+	
+	eval `opsi-admin -ds method getNetworkConfig_hash | grep nextBootServiceURL`
+	if [ "$nextBootServiceURL" = "" ]; then
+		/usr/bin/opsi-admin -d method setNetworkConfig `/usr/bin/opsi-admin -d method getNetworkConfig_hash | sed "s/\"nextBootServiceURL.*/\"nextBootServiceURL\" : \"https:\/\/${IPADDRESS}:4447\", /" | tr -d '\n' | sed "s/^/'/" | sed "s/$/'/"` "$DOMAIN"
+	fi
+	
+	chown opsiconfd:pcpatch /etc/opsi/pckeys
 	chmod 660 /etc/opsi/pckeys
-	chown pcpatch:pcpatch /etc/opsi/passwd
+	chown opsiconfd:pcpatch /etc/opsi/passwd
 	chmod 660 /etc/opsi/passwd
 	
 	db_get opsi/configure_dhcpd
