-

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,7 +1,7 @@
 #! /bin/bash -e
 
 # = = = = = = = = = = = = = = = = = = = = = = =
-# =  Copyright (C) 2006, 2007, 2008 uib GmbH  =
+# =       Copyright (C) 2010 uib GmbH         =
 # =           http://www.uib.de               =
 # =          All rights reserved.             =
 # = = = = = = = = = = = = = = = = = = = = = = =
@@ -33,245 +33,169 @@ db_get opsi/pcpatch_password1
 PCPATCH_PASSWORD=$RET
 
 case "$1" in
-    configure)
-	HOSTNAME=`uname -n | tr '[A-Z]' '[a-z]'`
-	DOMAIN=`hostname -d | tr '[A-Z]' '[a-z]'`
-	FQDN=`hostname --fqdn | tr '[A-Z]' '[a-z]'`
-	IPADDRESS=`getent hosts $FQDN | tail -n 1 | cut -d' ' -f1`
-	[ "$IPADDRESS" = "127.0.0.2" ] && IPADDRESS=""
-	
-	for iface in `ifconfig -a | grep "^[[:alnum:]]" | cut -d " " -f 1`; do
-		ip=`ifconfig $iface | grep "\:[[:digit:]]*\." | sed "s/:/ /g" | awk '{ printf $3}'`
-		NETMASK=`ifconfig $iface | grep "\:[[:digit:]]*\." | sed "s/:/ /g" | awk '{ printf $7}'`
-		GATEWAY=`route -n | grep ^0.0.0.0 | awk '{ printf $2}'`
-		if [ "$ip" != "" ]; then
-			if [ "$IPADDRESS" = "" ]; then
-				IPADDRESS="$ip"
+	configure)
+		HOSTNAME=`uname -n | tr '[A-Z]' '[a-z]'`
+		DOMAIN=`hostname -d | tr '[A-Z]' '[a-z]'`
+		FQDN=`hostname --fqdn | tr '[A-Z]' '[a-z]'`
+		IPADDRESS=`getent hosts $FQDN | tail -n 1 | cut -d' ' -f1`
+		[ $(echo $IPADDRESS | cut -d'.' -f1) = "127" ] && IPADDRESS=""
+		
+		for iface in `ifconfig -a | grep "^[[:alnum:]]" | cut -d " " -f 1`; do
+			ip=`ifconfig $iface | grep "\:[[:digit:]]*\." | sed "s/:/ /g" | awk '{ printf $3}'`
+			NETMASK=`ifconfig $iface | grep "\:[[:digit:]]*\." | sed "s/:/ /g" | awk '{ printf $7}'`
+			GATEWAY=`route -n | grep ^0.0.0.0 | awk '{ printf $2}'`
+			if [ "$ip" != "" ]; then
+				if [ "$IPADDRESS" = "" ]; then
+					IPADDRESS="$ip"
+				fi
+				[ "$IPADDRESS" = "$ip" ] && break
 			fi
-			[ "$IPADDRESS" = "$ip" ] && break
-		fi
-	done
-	
-	[ "$NETMASK" = "" ] && NETMASK="255.255.225.0"
-	
-	if [ "$IPADDRESS" != "" ]; then
-		for part in 1 2 3 4; do
-			I[$part]=$(echo $IPADDRESS | cut -d . -f $part)
-			M[$part]=$(echo $NETMASK | cut -d . -f $part)
 		done
 		
-		for part in 1 2 3 4; do
-			N[$part]=$((${I[$part]} & ${M[$part]}))
-			B[$part]=$((${N[$part]} | $((${M[$part]} ^255))))
-		done
+		[ "$NETMASK" = "" ] && NETMASK="255.255.225.0"
 		
-		SUBNET="${N[1]}.${N[2]}.${N[3]}.${N[4]}"
-		BROADCAST="${B[1]}.${B[2]}.${B[3]}.${B[4]}"
-	fi
-	
-	WINDOMAIN=`grep -i ^[[:space:]]*workgroup $SAMBA_CONF | cut -d'=' -f 2 | sed s'/ //g'`
-	
-	$VERBOSE && echo -e "\nSystem information"
-	$VERBOSE && echo "  -> IP-Address: $IPADDRESS"
-	$VERBOSE && echo "  -> Broadcast: $BROADCAST"
-	$VERBOSE && echo "  -> Netmask: $NETMASK"
-	$VERBOSE && echo "  -> Subnet: $SUBNET"
-	$VERBOSE && echo "  -> Gateway: $GATEWAY"
-	$VERBOSE && echo "  -> Hostname: $HOSTNAME"
-	$VERBOSE && echo "  -> Domain: $DOMAIN"
-	$VERBOSE && echo "  -> Fqdn: $FQDN"
-	$VERBOSE && echo "  -> Windomain: $WINDOMAIN"
-	
-	if [ `echo $FQDN | sed 's/\./ /g' | wc -w` -le 2 ]; then
-		echo -e "\nThe hostname $FQDN returned by 'hostname --fqdn' is not a fully qualified domain name"
-		echo "Opsi needs a fully qualified domain name in the form of <hostname>.<domain>.<tld>"
-		exit 1
-	fi
-	
-	if [ -f /var/lib/opsi/config/global.ini ]; then
-		set +e
-		grep "@HOSTNAME@" /var/lib/opsi/config/global.ini >/dev/null 2>/dev/null	
-		status=$?
-		set -e
-		if [ $status = 0 ]; then
-			cp /var/lib/opsi/config/global.ini /var/lib/opsi/config/global.ini.tmp
-			cat /var/lib/opsi/config/global.ini.tmp | sed "s/@HOSTNAME@/$HOSTNAME/g" > /var/lib/opsi/config/global.ini
-			rm /var/lib/opsi/config/global.ini.tmp
-		fi
-		set +e
-		grep "@WINDOMAIN@" /var/lib/opsi/config/global.ini >/dev/null 2>/dev/null	
-		status=$?
-		set -e
-		if [ $status = 0 ]; then
-			cp /var/lib/opsi/config/global.ini /var/lib/opsi/config/global.ini.tmp
-			cat /var/lib/opsi/config/global.ini.tmp | sed "s/@WINDOMAIN@/$WINDOMAIN/g" > /var/lib/opsi/config/global.ini
-			rm /var/lib/opsi/config/global.ini.tmp
-		fi
-		set +e
-		grep "@FQDN@" /var/lib/opsi/config/global.ini >/dev/null 2>/dev/null	
-		status=$?
-		set -e
-		if [ $status = 0 ]; then
-			cp /var/lib/opsi/config/global.ini /var/lib/opsi/config/global.ini.tmp
-			cat /var/lib/opsi/config/global.ini.tmp | sed "s/@FQDN@/$FQDN/g" > /var/lib/opsi/config/global.ini
-			rm /var/lib/opsi/config/global.ini.tmp
-		fi
-		set +e
-		grep "@IPADDRESS@" /var/lib/opsi/config/global.ini >/dev/null 2>/dev/null	
-		status=$?
-		set -e
-		if [ $status = 0 ]; then
-			cp /var/lib/opsi/config/global.ini /var/lib/opsi/config/global.ini.tmp
-			cat /var/lib/opsi/config/global.ini.tmp | sed "s/@IPADDRESS@/$IPADDRESS/g" > /var/lib/opsi/config/global.ini
-			rm /var/lib/opsi/config/global.ini.tmp
-		fi
-	fi
-	
-	if ! [ -e /var/lib/opsi/config/depots/$FQDN ]; then
-		mkdir -p /var/lib/opsi/config/depots/$FQDN
-	fi
-	
-	# file permissions
-	$VERBOSE && echo -e "\nSetting permissions..."
-	chown -R opsiconfd:pcpatch /etc/opsi/backendManager
-	chmod 0660 /etc/opsi/backendManager/*
-	chown -R opsiconfd:pcpatch /opt/pcbin/pcpatch
-	chmod 2770 /opt/pcbin/pcpatch
-	chown -R opsiconfd:pcpatch /opt/pcbin/pcpatch/pclog
-	chmod 2770 /opt/pcbin/pcpatch/pclog
-	chown -R opsiconfd:pcpatch /opt/pcbin/utils
-	chmod 2770 /opt/pcbin/utils
-	chown -R opsiconfd:pcpatch /opt/pcbin/install
-	chmod 2770 /opt/pcbin/install
-	chown -R opsiconfd:pcpatch /tftpboot/linux
-	chmod 2775 /tftpboot/linux
-	chmod 2775 /tftpboot/linux/pxelinux.cfg
-	find /tftpboot/linux -type f -exec chmod 664 {} \;
-	chown -R opsiconfd:pcpatch /var/lib/opsi
-	chmod 2750 /var/lib/opsi
-	# for ssh public key authentification to work rights on /var/lib/opsi have to be pcatch:pcpatch 750
-	chown pcpatch /var/lib/opsi
-	chmod 2770 /var/lib/opsi/products
-	chmod 0660 /var/lib/opsi/products/* >/dev/null 2>/dev/null || true
-	chmod 2770 /var/lib/opsi/config
-	chmod 2770 /var/lib/opsi/config/clients
-	chmod 2770 /var/lib/opsi/config/templates
-	chmod 2770 /var/lib/opsi/config/depots
-	chmod 2770 -R /var/lib/opsi/config/depots
-	find /var/lib/opsi/config/depots -type f -exec chmod 660 {} \;
-	chmod 2770 /var/lib/opsi/audit
-	chmod 0660 /var/lib/opsi/audit/* >/dev/null 2>/dev/null || true
-	chmod 0660 /var/lib/opsi/config/templates/pcproto.ini
-	chmod 0660 /var/lib/opsi/config/global.ini
-	chown opsiconfd:pcpatch /var/log/opsi
-	chmod 2770 /var/log/opsi
-	chown pcpatch:pcpatch /home/opsiproducts
-	chmod 2770 /home/opsiproducts
-	if [ "$CONFIGURE_SAMBA" = "true" ]; then
-		$VERBOSE && echo -e "\nConfiguring samba..."	
-		if [ -f $SAMBA_CONF ]; then
-			# Removing include created by opsi-depotserver < 3.3
-			cp $SAMBA_CONF $SAMBA_CONF.opsi-configure
-			cat $SAMBA_CONF.opsi-configure \
-				| grep -v '; load opsi shares' \
-				| grep -v 'include = /etc/samba/share.conf' \
-				> $SAMBA_CONF
-			rm $SAMBA_CONF.opsi-configure
+		if [ "$IPADDRESS" != "" ]; then
+			for part in 1 2 3 4; do
+				I[$part]=$(echo $IPADDRESS | cut -d . -f $part)
+				M[$part]=$(echo $NETMASK | cut -d . -f $part)
+			done
 			
-			$VERBOSE && echo "  -> Testing if share [opt_pcbin] already exists"
-			set +e
-			grep "^\[opt_pcbin\]" $SAMBA_CONF >/dev/null 2>/dev/null	
-			status=$?
-			set -e
-			if [ $status = 0 ]; then
-				$VERBOSE && echo "      * share exists"
-			else
-				$VERBOSE && echo "      * adding share"
-				echo "" 				>> $SAMBA_CONF
-				echo "[opt_pcbin]" 			>> $SAMBA_CONF
-				echo " available = yes" 		>> $SAMBA_CONF
-				echo " comment = opsi depot share" 	>> $SAMBA_CONF
-				echo " path = /opt/pcbin" 		>> $SAMBA_CONF
-				echo " oplocks = no" 			>> $SAMBA_CONF
-				echo " level2 oplocks = no"  		>> $SAMBA_CONF
-				echo " writeable = yes" 		>> $SAMBA_CONF
-				echo " invalid users = root" 		>> $SAMBA_CONF
-			fi
+			for part in 1 2 3 4; do
+				N[$part]=$((${I[$part]} & ${M[$part]}))
+				B[$part]=$((${N[$part]} | $((${M[$part]} ^255))))
+			done
 			
-			$VERBOSE && echo "  -> Testing if share [opsi_config] already exists"
-			set +e
-			grep "^\[opsi_config\]" $SAMBA_CONF >/dev/null 2>/dev/null
-			status=$?
-			set -e
-			if [ $status = 0 ]; then
-				$VERBOSE && echo "      * share exists"
-			else
-				$VERBOSE && echo "      * adding share"
-				echo "" 				>> $SAMBA_CONF
-				echo "[opsi_config]" 			>> $SAMBA_CONF
-				echo " available = yes"			>> $SAMBA_CONF
-				echo " comment = opsi config share" 	>> $SAMBA_CONF
-				echo " path = /var/lib/opsi/config" 	>> $SAMBA_CONF
-				echo " writeable = yes" 		>> $SAMBA_CONF
-				echo " invalid users = root" 		>> $SAMBA_CONF
-			fi
-			
-			$VERBOSE && echo "  -> Testing if share [opsi_workbench] already exists"
-			set +e
-			grep "^\[opsi_workbench\]" $SAMBA_CONF >/dev/null 2>/dev/null
-			status=$?
-			set -e
-			if [ $status = 0 ]; then
-				$VERBOSE && echo "      * share exists"
-			else
-				$VERBOSE && echo "      * adding share"
-				echo "" 				>> $SAMBA_CONF
-				echo "[opsi_workbench]" 		>> $SAMBA_CONF
-				echo " available = yes"			>> $SAMBA_CONF
-				echo " comment = opsi workbench" 	>> $SAMBA_CONF
-				echo " path = /home/opsiproducts" 	>> $SAMBA_CONF
-				echo " writeable = yes" 		>> $SAMBA_CONF
-				echo " invalid users = root" 		>> $SAMBA_CONF
-				echo " create mask = 0660"		>> $SAMBA_CONF
-				echo " directory mask = 0770"		>> $SAMBA_CONF
-			fi
-		else
-			echo "        * $SAMBA_CONF not found!"
-			echo "        * you will have to configure samba manually!"
-			echo "        * look in /usr/share/opsi-depotserver for examples."
+			SUBNET="${N[1]}.${N[2]}.${N[3]}.${N[4]}"
+			BROADCAST="${B[1]}.${B[2]}.${B[3]}.${B[4]}"
 		fi
-	fi
-	
-	if [ "$CONFIGURE_DHCPD" = "true" ]; then
-		# dhcp-server
-		echo -e "\nConfiguring dhcpd..."
-		if [ -f $DHCPD_CONF ]; then
-			set +e
-			cat $DHCPD_CONF | grep "ldap-server" >/dev/null 2>/dev/null	
-			status=$?
-			set -e
-			if [ $status = 0 ]; then
-				$VERBOSE && echo "        * DHCPD configured by LDAP, leaving as is!"
+		
+		WINDOMAIN=`grep -i ^[[:space:]]*workgroup $SAMBA_CONF | cut -d'=' -f 2 | sed s'/ //g'`
+		
+		$VERBOSE && echo -e "\nSystem information"
+		$VERBOSE && echo "  -> IP-Address: $IPADDRESS"
+		$VERBOSE && echo "  -> Broadcast: $BROADCAST"
+		$VERBOSE && echo "  -> Netmask: $NETMASK"
+		$VERBOSE && echo "  -> Subnet: $SUBNET"
+		$VERBOSE && echo "  -> Gateway: $GATEWAY"
+		$VERBOSE && echo "  -> Hostname: $HOSTNAME"
+		$VERBOSE && echo "  -> Domain: $DOMAIN"
+		$VERBOSE && echo "  -> Fqdn: $FQDN"
+		$VERBOSE && echo "  -> Windomain: $WINDOMAIN"
+		
+		if [ `echo $FQDN | sed 's/\./ /g' | wc -w` -le 2 ]; then
+			echo -e "\nThe hostname $FQDN returned by 'hostname --fqdn' is not a fully qualified domain name"
+			echo "Opsi needs a fully qualified domain name in the form of <hostname>.<domain>.<tld>"
+			exit 1
+		fi
+		
+		if [ "$CONFIGURE_SAMBA" = "true" ]; then
+			$VERBOSE && echo -e "\nConfiguring samba..."
+			if [ -f $SAMBA_CONF ]; then
+				# Removing include created by opsi-depotserver < 3.3
+				cp $SAMBA_CONF $SAMBA_CONF.opsi-configure
+				cat $SAMBA_CONF.opsi-configure \
+					| grep -v '; load opsi shares' \
+					| grep -v 'include = /etc/samba/share.conf' \
+					> $SAMBA_CONF
+				rm $SAMBA_CONF.opsi-configure
+				
+				$VERBOSE && echo "  -> Testing if share [opt_pcbin] already exists"
+				set +e
+				grep "^\[opt_pcbin\]" $SAMBA_CONF >/dev/null 2>/dev/null	
+				status=$?
+				set -e
+				if [ $status = 0 ]; then
+					$VERBOSE && echo "      * share exists"
+				else
+					$VERBOSE && echo "      * adding share"
+					echo "" 				>> $SAMBA_CONF
+					echo "[opt_pcbin]" 			>> $SAMBA_CONF
+					echo " available = yes" 		>> $SAMBA_CONF
+					echo " comment = opsi depot share" 	>> $SAMBA_CONF
+					echo " path = /opt/pcbin" 		>> $SAMBA_CONF
+					echo " oplocks = no" 			>> $SAMBA_CONF
+					echo " level2 oplocks = no"  		>> $SAMBA_CONF
+					echo " writeable = yes" 		>> $SAMBA_CONF
+					echo " write list = @opsiadmin" 	>> $SAMBA_CONF
+					echo " invalid users = root" 		>> $SAMBA_CONF
+				fi
+				
+				$VERBOSE && echo "  -> Testing if share [opsi_config] already exists"
+				set +e
+				grep "^\[opsi_config\]" $SAMBA_CONF >/dev/null 2>/dev/null
+				status=$?
+				set -e
+				if [ $status = 0 ]; then
+					$VERBOSE && echo "      * share exists"
+				else
+					$VERBOSE && echo "      * adding share"
+					echo "" 				>> $SAMBA_CONF
+					echo "[opsi_config]" 			>> $SAMBA_CONF
+					echo " available = yes"			>> $SAMBA_CONF
+					echo " comment = opsi config share" 	>> $SAMBA_CONF
+					echo " path = /var/lib/opsi/config" 	>> $SAMBA_CONF
+					echo " writeable = yes" 		>> $SAMBA_CONF
+					echo " write list = @opsiadmin" 	>> $SAMBA_CONF
+					echo " invalid users = root" 		>> $SAMBA_CONF
+				fi
+				
+				$VERBOSE && echo "  -> Testing if share [opsi_workbench] already exists"
+				set +e
+				grep "^\[opsi_workbench\]" $SAMBA_CONF >/dev/null 2>/dev/null
+				status=$?
+				set -e
+				if [ $status = 0 ]; then
+					$VERBOSE && echo "      * share exists"
+				else
+					$VERBOSE && echo "      * adding share"
+					echo "" 				>> $SAMBA_CONF
+					echo "[opsi_workbench]" 		>> $SAMBA_CONF
+					echo " available = yes"			>> $SAMBA_CONF
+					echo " comment = opsi workbench" 	>> $SAMBA_CONF
+					echo " path = /home/opsiproducts" 	>> $SAMBA_CONF
+					echo " writeable = yes" 		>> $SAMBA_CONF
+					echo " write list = @opsiadmin" 	>> $SAMBA_CONF
+					echo " invalid users = root" 		>> $SAMBA_CONF
+					echo " create mask = 0660"		>> $SAMBA_CONF
+					echo " directory mask = 0770"		>> $SAMBA_CONF
+				fi
 			else
-				extension=`date +%F_%R`
-				$VERBOSE && echo "        * Saving current dhcpd.conf to dhcpd.conf.$extension"
-				cp -p $DHCPD_CONF $DHCPD_CONF.$extension
-				$VERBOSE && echo "        * Patching dhcpd.conf"
-				cat << EOF | /usr/bin/python
+				echo "        * $SAMBA_CONF not found!"
+				echo "        * you will have to configure samba manually!"
+				echo "        * look in /usr/share/opsi-depotserver for examples."
+			fi
+		fi
+	
+		if [ "$CONFIGURE_DHCPD" = "true" ]; then
+			# dhcp-server
+			echo -e "\nConfiguring dhcpd..."
+			if [ -f $DHCPD_CONF ]; then
+				set +e
+				cat $DHCPD_CONF | grep "ldap-server" >/dev/null 2>/dev/null	
+				status=$?
+				set -e
+				if [ $status = 0 ]; then
+					$VERBOSE && echo "        * DHCPD configured by LDAP, leaving as is!"
+				else
+					extension=`date +%F_%R`
+					$VERBOSE && echo "        * Saving current dhcpd.conf to dhcpd.conf.$extension"
+					cp -p $DHCPD_CONF $DHCPD_CONF.$extension
+					$VERBOSE && echo "        * Patching dhcpd.conf"
+					cat << EOF | /usr/bin/python
 import sys
-from OPSI.Backend.DHCPD import *
+from OPSI.Util.File import DHCPDConfFile
 
 nextserver = "$IPADDRESS"
-filename = "linux/pxelinux.0"
-subnet = "$SUBNET"
-netmask = "$NETMASK"
+filename   = "linux/pxelinux.0"
+subnet     = "$SUBNET"
+netmask    = "$NETMASK"
 
-config = Config("$DHCPD_CONF")
-config._parseConfig()
+config = DHCPDConfFile("$DHCPD_CONF")
+config.parse()
 
 print ""
 
-if config._globalBlock.getParameters_hash().get('use-host-decl-names', False):
+if config.getGlobalBlock().getParameters_hash().get('use-host-decl-names', False):
 	print "               use-host-decl-names already enabled"
 else:
 	p = Parameter(
@@ -281,7 +205,7 @@ else:
 		value 		= True )
 	config._globalBlock.addComponent(p)
 
-subnets = config._globalBlock.getBlocks('subnet', recursive = True)
+subnets = config.getGlobalBlock().getBlocks('subnet', recursive = True)
 if not subnets:
 	print "                  no subnets found, adding subnet"
 	config._globalBlock.addComponent(
@@ -292,7 +216,7 @@ if not subnets:
 			settings 	= ['subnet', subnet, 'netmask', netmask] )
 	)
 
-for subnet in config._globalBlock.getBlocks('subnet', recursive = True):
+for subnet in config.getGlobalBlock().getBlocks('subnet', recursive = True):
 	print "\n               Subnet %s/%s found" % (subnet.settings[1], subnet.settings[3])
 	groups = subnet.getBlocks('group')
 	if not groups:
@@ -327,83 +251,54 @@ for subnet in config._globalBlock.getBlocks('subnet', recursive = True):
 					key 		= 'filename',
 					value 		= filename ) )
 			print "                     filename set to %s" % filename
-config.writeConfig()
+config.generate()
 print ""
 EOF
 
-			chown root:pcpatch $DHCPD_CONF
-			chmod 664 $DHCPD_CONF
+				chown root:pcpatch $DHCPD_CONF
+				chmod 664 $DHCPD_CONF
+				fi
+			else
+				echo "        * $DHCPD_CONF not found!"
+				echo "        * you will have to configure dhcpd manually!"
+				echo "        * look in /usr/share/opsi-depotserver for examples."
 			fi
-		else
-			echo "        * $DHCPD_CONF not found!"
-			echo "        * you will have to configure dhcpd manually!"
-			echo "        * look in /usr/share/opsi-depotserver for examples."
 		fi
-	fi
 	
-	set +e
-	cat /etc/sudoers | grep "$DHCPD_INIT restart" >/dev/null 2>/dev/null	
-	status=$?
-	set -e
-	if [ $status = 0 ]; then
-		rm /tmp/sudoers 2>/dev/null || true
-		touch /tmp/sudoers
-		chmod 600 /tmp/sudoers
-		cat /etc/sudoers > /tmp/sudoers
-		cat /tmp/sudoers | grep -v "$DHCPD_INIT restart" > /etc/sudoers
-		rm /tmp/sudoers
-	fi
-	echo "opsiconfd ALL=NOPASSWD: $DHCPD_INIT restart" >> /etc/sudoers
-	
-	touch /etc/opsi/pckeys
-	touch /etc/opsi/passwd
-	
-	set +e
-	/usr/bin/opsi-admin -d method getPcpatchPassword $FQDN >/dev/null 2>/dev/null	
-	status=$?
-	set -e
-	if [ $status != 0 ]; then
-		# No password set
-		/usr/bin/opsi-admin -d method createOpsiBase >/dev/null 2>/dev/null	
+		set +e
+		cat /etc/sudoers | grep "$DHCPD_INIT restart" >/dev/null 2>/dev/null	
+		status=$?
+		set -e
+		if [ $status = 0 ]; then
+			rm /tmp/sudoers 2>/dev/null || true
+			touch /tmp/sudoers
+			chmod 600 /tmp/sudoers
+			cat /etc/sudoers > /tmp/sudoers
+			cat /tmp/sudoers | grep -v "$DHCPD_INIT restart" > /etc/sudoers
+			rm /tmp/sudoers
+		fi
+		echo "opsiconfd ALL=NOPASSWD: $DHCPD_INIT restart" >> /etc/sudoers
 		
-		/usr/bin/opsi-admin -d method createServer "$HOSTNAME" "$DOMAIN" > /dev/null
+		if [ "$CONFIGURE_DHCPD" = "true" ]; then
+			echo "Restarting dhcp server..."
+			$DHCPD_INIT restart >/dev/null 2>/dev/null || true
+		fi
 		
-		/usr/bin/opsi-admin -d task setPcpatchPassword $PCPATCH_PASSWORD
-	fi
+		if [ "$CONFIGURE_SAMBA" = "true" ]; then
+			echo "Reloading samba..."
+			$SAMBA_INIT reload >/dev/null 2>/dev/null || true
+		fi
 	
-	test -e /var/lib/opsi/.ssh && rm -r /var/lib/opsi/.ssh
-	/usr/bin/opsi-admin -d method getPcpatchRSAPrivateKey >/dev/null 2>/dev/null || true
+	;;
 	
-	eval `opsi-admin -ds method getNetworkConfig_hash | grep nextBootServiceURL`
-	if [ "$nextBootServiceURL" = "" ]; then
-		/usr/bin/opsi-admin -d method setNetworkConfig `/usr/bin/opsi-admin -d method getNetworkConfig_hash | sed "s/\"nextBootServiceURL.*/\"nextBootServiceURL\" : \"https:\/\/${IPADDRESS}:4447\", /" | tr -d '\n' | sed "s/^/'/" | sed "s/$/'/"` "$DOMAIN"
-	fi
+	abort-upgrade|abort-remove|abort-deconfigure)
 	
-	chown opsiconfd:pcpatch /etc/opsi/pckeys
-	chmod 660 /etc/opsi/pckeys
-	chown opsiconfd:pcpatch /etc/opsi/passwd
-	chmod 660 /etc/opsi/passwd
-	
-	if [ "$CONFIGURE_DHCPD" = "true" ]; then
-		echo "Restarting dhcp server..."
-		$DHCPD_INIT restart >/dev/null 2>/dev/null || true
-	fi
-	
-	if [ "$CONFIGURE_SAMBA" = "true" ]; then
-		echo "Reloading samba..."
-		$SAMBA_INIT reload >/dev/null 2>/dev/null || true
-	fi
-	
-    ;;
-    
-    abort-upgrade|abort-remove|abort-deconfigure)
+	;;
 
-    ;;
-
-    *)
-        echo "postinst called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
+	*)
+		echo "postinst called with unknown argument \`$1'" >&2
+		exit 1
+	;;
 esac
 
 db_stop
